### ISSUE TITLE
make components themable

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-ui#34]
it's silly to pass down props such as "color" when `ThemeProvider` and `theme` allow us to use a cleaner and easier syntax.

This bumps the minor.

### Tasks:

- [x] Anchor bbe7203f04729e04bb662de9fecc263e5e8e3185
- [x] BoxedContent 634815f2a85898c5040677e9c728dd618d4680ac (follow-up c6776b917b35660b0690e2b1204dd5c7523bc76c)
- [x] Clock 763feadb0fdcf5b0ce59e760abdd332ee768d890
- [x] ~~ContentToggleArrow~~ N/A
- [x] DataBlock 346cf1fba362ec156c3ccc62e519bd89dff9b247
- [x] GridSystem ba5959751e2074420ee975425087074aa81b0f99
- [x] Headings 820b07b8142cde12ec04cbdecc96cd46f09b0125 (follow-up 7c7a05c6f92d5dabfc65e1feb7d70de1c1000f46)
- [x] MediaContent ea8fb0a60b11daefdec483b0a4bcc27a9d4279d6
- [x] Page 0643b3f4ac0bd85a0d92ae7af2d2e4d0c3885986
- [x] Paragraph e437f9f9844fae806fe14c325c3f7b81022286c4
- [x] PushButton bfdb9105fdd369d6bc5f0bf7cdb22a6e50c019eb
- [x] ~~SelectOption~~ N/A
- [x] ~~Separator~~ N/A
- [x] ~~SwitchButton~~ N/A
- [x] TextLabel 3c6064ae53a1429dd9a483d5f7a59a9b2a2167e0
- [x] UnstyledButton dc2efc8e391bf8df723d5b0165a54c5d93b9ffaf

**Comment by cezaraugusto** [comment]
closed after 9e6c374a6ed5c64ea77f696c7b59be9e1742e82e
